# Generated by Django 5.1.3 on 2024-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='attachments',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('installation', 'Installation'), ('maintenance', 'Maintenance'), ('repair', 'Repair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
